site_name: DHRIFT Documentation
theme:
  name: readthedocs
  # favicon: img/favicon.ico
nav:
 - Home: 'home.md'
 - About: 'about.md'
 - What is DHRIFT?: 'whatis.md'
 - How does DHRIFT work?: 'howdhrift.md'
 - Features: 'features.md'
 - Learning with DHRIFT: 'learn.md'
 - Teaching Tips: 'teaching.md'
 - Anatomy of a Workshop: 'workshopanatomy.md'
 - Customizing a DHRIFT Institute: 'customize.md'
 - Modifying a DHRIFT workshop: 'modifyworkshop.md'
 - Creating a DHRIFT workshop: 'createworkshop.md'
 - Working with the Glossary: 'glossary.md'
 - Workshop Guidelines: 'workshop-guidelines.md'
 - Propose and Submit a Workshop: 'propose-submit.md'

extra_css:
  -_static/custom.css

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
